version: '3'

services:
  scaffold:
    container_name: QQBot
    build:
      context: .
      dockerfile: Dockerfile  # 指定你的 Dockerfile 文件路径
    ports:
      - "8081:8081"
    volumes:
      - ../QQBot-statics/img:/app/statics/img  # 将本地图片文件夹挂载到容器中的对应路径

