version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: liuzihao520
      MYSQL_DATABASE: upload
      LANG: C.UTF-8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 注意这里的路径映射
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  blog:
    build:
      context: .
      dockerfile: Dockerfile  # 指定你的 Dockerfile 文件路径
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./scaffold-statics//img:/app/statics/img  # 将本地图片文件夹挂载到容器中的对应路径
volumes:
  mysql_data:
  redis_data:
