version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: scaffold_mysql
    environment:
      MYSQL_ROOT_PASSWORD: liuzihao520
      MYSQL_DATABASE: scaffold
      LANG: C.UTF-8
        - TZ=Asia/Shanghai
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 注意这里的路径映射  默认情况下，MySQL容器的入口脚本会自动执行/docker-entrypoint-initdb.d/目录下的SQL文件。
      - mysql_data_scaffold:/var/lib/mysql
    ports:
      - "3308:3306"
  redis:
    image: redis:latest
    container_name: scaffold_redis
    ports:
      - "26379:6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis_data_scaffold:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./log/redis.log:/log/redis.log
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
  blog:
    container_name: scaffold
    build:
      context: .
      dockerfile: Dockerfile  # 指定你的 Dockerfile 文件路径
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    volumes:
      - ../scaffold-statics/img:/app/statics/img  # 将本地图片文件夹挂载到容器中的对应路径
volumes:
  mysql_data_scaffold:
  redis_data_scaffold:
