app:
  name: "scaffold"
  mode: "dev"
  port: "80"
  start_time: "2024-03-27"
  machine_id: 1
auth:
  jwt_expire: 168 #一周时间
log:
  level: "info"
  filename: "./log/scaffold.log"
  max_size: 1
  max_age: 30
  max_backups: 7
mysql:
  host: mysql
  username: "root"
  password: liuzihao520
  port: "3306"
  dbname: "scaffold"
  max_open_con: 200
  max_idle_con: 50
redis:
  host: redis
  db: 0
  password: 520liuzihao
  poll_size: 100